const LOG_TYPE_LOGIN = 1
const LOG_TYPE_LOGOUT = 2
const LOG_TYPE_PURCHASE = 3
const LOG_TYPE_PROFILE_UPDATED = 4
const LOG_TYPE_PWD_CHANGED = 5

module.exports {
    LOG_TYPE_LOGIN,LOG_TYPE_LOGOUT, LOG_TYPE_PROFILE_UPDATED,LOG_TYPE_PURCHASE,LOG_TYPE_PWD_CHANGED
}